### ISSUE TITLE
bug: remaining effort on initial report creation is buggy

### ISSUE THREAD

**Issue by derrabauke** [adfinis/timed-backend#933]
## Scenario
Create a report and add an estimated remaining effort to it.

## Expected behavior
It updates the remaining effort of the certain task in the statistics view.

## Actual behavior
After submitting the report the remaining effort does **not** update in stats view. But after editing the rem. effort and saving the report again in the timesheet, it will update the values in the stats view.

The attributes are fine in both requests to the backend. I suspect that a the `POST` and `PATCH` requests have different handling of the remaining effort attribute. Maybe the `POST` does not properly trigger the update?
![image](https://user-images.githubusercontent.com/10029904/219358043-268b4856-1b2e-430a-b4f0-e9891d1f799e.png)

**Comment by trowik** [comment]
Yes, you're totally right. The signal to update `remaining_effort` isn't properly triggered when creating a report.
Fix is on the way.
